// Fallback quotes used when remote quote APIs are unavailable
export const fallbackQuotes = [
  "Don't panic. — Douglas Adams",
  "Reality is frequently inaccurate. — Douglas Adams",
  "The cosmos is within us. We are made of star-stuff. — Carl Sagan",
  "Books break the shackles of time. — Carl Sagan",
  "Everything was beautiful, and nothing hurt. — Kurt Vonnegut",
  "So it goes. — Kurt Vonnegut",
  "We are what we pretend to be, so we must be careful about what we pretend to be. — Kurt Vonnegut",
  "We are all in the gutter, but some of us are looking at the stars. — Oscar Wilde",
  "Without hope, there is no adventure. — Ray Bradbury",
  "You don't have to burn books to destroy a culture. Just get people to stop reading them. — Ray Bradbury",
  "Any sufficiently advanced technology is indistinguishable from magic. — Arthur C. Clarke",
  "Violence is the last refuge of the incompetent. — Isaac Asimov",
  "The future is already here—it's just not evenly distributed. — William Gibson",
  "Stories are light. Light is precious in a world so dark. — Kate DiCamillo",
  "You cannot open a book without learning something. — Confucius",
  "Words can be like X-rays if you use them properly—they'll go through anything. — Aldous Huxley",
  "People think that stories are shaped by people. In fact, it's the other way around. — Terry Pratchett",
  "A reader lives a thousand lives before he dies. — George R.R. Martin",
  "There is no friend as loyal as a book. — Ernest Hemingway",
  "She read books as one would breathe air. — Annie Dillard",
  "The most technologically efficient machine that man has ever invented is the book. — Northrop Frye",
  "A room without books is like a body without a soul. — Marcus Tullius Cicero",
  "I have always imagined that Paradise will be a kind of library. — Jorge Luis Borges",
  "Once you learn to read, you will be forever free. — Frederick Douglass",
  "To read is to voyage through time. — Carl Sagan",
  "The man who does not read has no advantage over the man who cannot read. — Mark Twain",
  "You want weapons? We’re in a library! Books! The best weapons in the world! — The Doctor",
  "A book is a dream that you hold in your hand. — Neil Gaiman",
  "Reading is to the mind what exercise is to the body. — Joseph Addison",
  "Sleep is good, he said, and books are better. — George R.R. Martin",
  "We read to know we are not alone. — C.S. Lewis",
  "The world was hers for the reading. — Betty Smith",
  "The only thing that you absolutely have to know, is the location of the library. — Albert Einstein",
  "It is what you read when you don't have to that determines what you will be. — Oscar Wilde",
  "A mind needs books as a sword needs a whetstone. — George R.R. Martin",
  "Books are uniquely portable magic. — Stephen King",
  "Libraries were full of ideas—perhaps the most dangerous and powerful of all weapons. — Sarah J. Maas",
  "All we have to decide is what to do with the time that is given us. — J.R.R. Tolkien",
  "Not all those who wander are lost. — J.R.R. Tolkien",
  "We are cups, constantly and quietly being filled. The trick is knowing how to tip ourselves over and let the beautiful stuff out. — Ray Bradbury",
  "Fantasy is a necessary ingredient in living. — Dr. Seuss",
  "If you only read the books that everyone else is reading, you can only think what everyone else is thinking. — Haruki Murakami",
  "Books are mirrors: you only see in them what you already have inside you. — Carlos Ruiz Zafón",
  "The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid. — Jane Austen",
  "Words are our most inexhaustible source of magic. — Albus Dumbledore",
  "The universe is made of stories, not of atoms. — Muriel Rukeyser",
  "There is no surer foundation for a beautiful friendship than a mutual taste in literature. — P.G. Wodehouse",
  "We live and breathe words. — Cassandra Clare",
  "Until I feared I would lose it, I never loved to read. One does not love breathing. — Harper Lee",
  "Reading brings us unknown friends. — Honoré de Balzac",
  "Stories are the wildest things of all. — Patrick Ness",
  "What is the use of a book, without pictures or conversations? — Lewis Carroll",
  "Humans see what they want to see. — Kurt Vonnegut",
  "Science is not only a disciple of reason but, also, one of romance and passion. — Stephen Hawking",
  "Somewhere, something incredible is waiting to be known. — Carl Sagan",
  "If you can't explain it simply, you don't understand it well enough. — Albert Einstein",
  "The good thing about science is that it's true whether or not you believe in it. — Neil deGrasse Tyson",
  "In the beginning was the Word, and the Word was with God, and the Word was God. — Gospel of John",
  "There is no frigate like a book to take us lands away. — Emily Dickinson",
  "The library is inhabited by spirits that come out of the pages at night. — Isabel Allende",
  "When in doubt, go to the library. — Ron Weasley",
  "Reading furnishes the mind only with materials of knowledge; it is thinking that makes what we read ours. — John Locke",
  "\"Iqra\" — the first word of the Quran; it means to \"Read.\"",
  "The reading of all good books is like a conversation with the finest minds of past centuries. — René Descartes",
  "Good friends, good books, and a sleepy conscience: this is the ideal life. — Mark Twain",
  "Never trust anyone who has not brought a book with them. — Lemony Snicket",
  "We lose ourselves in books, we find ourselves there too. — Anonymous",
  "Books are not made to be believed, but to be subjected to inquiry. — Umberto Eco",
  "A classic is a book that has never finished saying what it has to say. — Italo Calvino",
  "I cannot remember the books I've read any more than the meals I have eaten; even so, they have made me. — Ralph Waldo Emerson",
  "Reading is an exercise in empathy; an exercise in walking in someone else's shoes for a while. — Malorie Blackman",
  "No two persons ever read the same book. — Edmund Wilson",
  "Books are the plane, and the train, and the road. They are the destination and the journey. — Anna Quindlen",
  "I do believe something very magical can happen when you read a good book. — J.K. Rowling",
  "The world is a book and those who do not travel read only one page. — Saint Augustine",
  "There are worse crimes than burning books. One of them is not reading them. — Joseph Brodsky",
  "If you only read one book a year, the world is too small for you. — Anonymous",
  "Literature is the most agreeable way of ignoring life. — Fernando Pessoa",
  "Books are the treasured wealth of the world and the fit inheritance of generations and nations. — Henry David Thoreau",
  "A book must be the axe for the frozen sea within us. — Franz Kafka",
  "Some books are so familiar that reading them is like being home again. — Louisa May Alcott",
  "Books are lighthouses erected in the great sea of time. — E.P. Whipple",
  "A half-read book is a half-finished love affair. — David Mitchell",
  "Reading should not be presented to children as a chore, but as a gift. — Kate DiCamillo",
  "To acquire the habit of reading is to construct for yourself a refuge from almost all the miseries of life. — W. Somerset Maugham",
  "You are never alone when you are reading a book. — Susan Wiggs",
  "A word after a word after a word is power. — Margaret Atwood",
  "You can never get a cup of tea large enough or a book long enough to suit me. — C.S. Lewis",
  "Books serve to show a man that those original thoughts of his aren't very new after all. — Abraham Lincoln",
  "My best friend is a person who will give me a book I have not read. — Abraham Lincoln",
  "There is more treasure in books than in all the pirate's loot on Treasure Island. — Walt Disney",
  "A book is proof that humans are capable of working magic. — Carl Sagan",
  "Books are the quietest and most constant of friends. — Charles W. Eliot",
  "An hour spent reading is one stolen from paradise. — Thomas Wharton",
  "Reading is departure and arrival. — Terri Guillemets"
];

export function pickRandomQuote() {
  return fallbackQuotes[Math.floor(Math.random() * fallbackQuotes.length)];
}
